// starters/react-starter/src/App.jsx
import { useState } from 'react'

function App() {
  const [tasks, setTasks] = useState([])

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>TaskFlow (React Starter)</h1>
      <p>Bienvenue dans votre projet de gestion de tâches.</p>
      
      <div style={{ marginBottom: '20px' }}>
        <input type="text" placeholder="Nouvelle tâche..." />
        <button>Ajouter</button>
      </div>

      <ul>
        <li>Exemple de tâche (à remplacer par vos composants)</li>
      </ul>
    </div>
  )
}

export default App

// starters/vue-starter/src/App.vue
<script setup>
import { ref } from 'vue'
const tasks = ref([])
</script>

<template>
  <div style="padding: 20px; font-family: sans-serif;">
    <h1>TaskFlow (Vue Starter)</h1>
    <p>Bienvenue dans votre projet de gestion de tâches.</p>

    <div style="margin-bottom: 20px;">
      <input type="text" placeholder="Nouvelle tâche..." />
      <button>Ajouter</button>
    </div>

    <ul>
      <li>Exemple de tâche (à remplacer par vos composants)</li>
    </ul>
  </div>
</template>

<style scoped>
/* Vos styles ici */
</style>
